### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by Azmodan95** [essserrr/hotel#13]
При сужении футера колонки в нем начинают слипаться. Так же в макетах есть мобильная версия футера, но я не вижу чтобы она появлялась.
![screenshot-localhost_3000-2021 04 30-11_36_56](https://user-images.githubusercontent.com/51163508/116670436-650eca00-a9a8-11eb-8a6f-2ee7db2afc54.png)

---

На странице room-details при сужении картинки становятся слишком большими, нужно с этим что-то сделать. Еще на этой странице контент не помещается в ширину 320px.

---

Нужно убрать возможно выделения текста на кнопках. И так же неплохо было бы добавить всем интерактивным элементам hover.

**Comment by essserrr** [comment]
Пофикшено
