### ISSUE TITLE
Передаваемые имена модификаторов

### ISSUE THREAD

**Issue by Azmodan95** [essserrr/hotel#15]
https://github.com/essserrr/hotel/blob/76a814853842f9b737da3706aa4b7c69e430b509/src/components/buttons/button/button.pug#L3
Не очень надежная штука, по причине того что мы в данном случае полагаемся на то что нам придется действительно корректное имя модификатора. Плюс ко всему вообще не понятно какие варианты нам доступны, чтобы это понять надо просматривать стили. В данном случае лучше использовать объект:
`const styleVariant = { outlined: 'ui-button--outlined', noFill: 'ui-button--nofill'}`
Объединить все классы можно с помощью массива:
`const classes = ['ui-button', styleVariant[variant], sizeVariant[size]]`
Ну и затем уже использовать:
`class=classes`
В этом случае, зайдя в блок мы сразу будем видеть возможные варианты стилизации, мы не сможем задать не допустимое имя класса, если будет передано не существующее имя модификатора класс попросту не будет добавлен.

**Comment by Azmodan95** [comment]
https://github.com/essserrr/hotel/blob/2988e7ba22c43bc622b79ee5865551c0d252100b/src/components/buttons/like/like.pug#L3
К булевым модификатором, создавать объект не стоит, так как там в зависимости от значения мы добавляем класс или нет, тут по сути один вариант, подобное стоит применять только модификатором по ключу. 
https://github.com/essserrr/hotel/blob/2988e7ba22c43bc622b79ee5865551c0d252100b/src/components/buttons/like/like.pug#L4
Использовать join не обязательно, так как pug поддерживает массивы для задания классов.
https://github.com/essserrr/hotel/blob/2988e7ba22c43bc622b79ee5865551c0d252100b/src/components/checkbox/checkbox.pug#L6
Так же в некоторых моментах, переделал, но забыл передать в атрибут

**Comment by Azmodan95** [comment]
https://github.com/essserrr/hotel/blob/d033ac7c71da65b5be0a2a5955e95df6bb10db9d/src/components/buttons/like/like.pug#L3
Один момент, почему в переменной checked строка, а не булевое значение?

**Comment by essserrr** [comment]
> https://github.com/essserrr/hotel/blob/d033ac7c71da65b5be0a2a5955e95df6bb10db9d/src/components/buttons/like/like.pug#L3
> 
> 
> Один момент, почему в переменной checked строка, а не булевое значение?

Не помню деталей, но почему то c true галка не проставлялась. Пофикшено. Вроде все работает
