### ISSUE TITLE
Модули

### ISSUE THREAD

**Issue by Azmodan95** [essserrr/hotel#17]
https://github.com/essserrr/hotel/blob/2988e7ba22c43bc622b79ee5865551c0d252100b/package.json#L17
А все установленные модули используются? Нужно оставить только те модули нужны и используются. И так же нужно отсортировать модули, поместить в dependencies модули без которых готовый проект не сможет работать, а в devDependencies модули которые нужны только для разработки.

**Comment by Azmodan95** [comment]
https://github.com/essserrr/hotel/blob/74596e7c87b42c233de518c370417f1ccb9e04e8/package.json#L48
Не заметил, в dependencies появились два модуля которые скорее относятся к разработке. И еще jquery все таки нужно перенести в dependencies, так как ведь если он используется готовый проект без него будет работать не корректно.

**Comment by essserrr** [comment]
Пофикшено
