### ISSUE TITLE
js- префиксы

### ISSUE THREAD

**Issue by a-poluhin** [essserrr/hotel#7]
По стандарту все выражения, которые используются для поиска по DOM, должны иметь префикс js-
![image](https://user-images.githubusercontent.com/10168007/112433137-67ac4d00-8d74-11eb-8bef-f768489d29d3.png)

**Comment by essserrr** [comment]
Данный узел создается библиотекой и я не могу повлиять на его именование, но  я еще раз просмотрю все остальные
